// Copyright (c) 2023 Tom Hancocks
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#include <libFoundation/hashing/hashing.hpp>
#include <libTesting/testing.hpp>

TEST(hashed_string_returnsCorrectValue)
{
    // Additional values could be added here to help ensure edge cases are correctly
    // hashed.
    // Any expected hash values should be generated by a third party hashing algorithm
    // to ensure we aren't validating against our self. These were generated using
    // https://asecuritysite.com/encryption/xxHash
    test::equal(foundation::hashing::string("apple"), 0x5889a1c15c94729f);
    test::equal(foundation::hashing::string("banana"), 0xcef162e1813c8ce2);
    test::equal(foundation::hashing::string("orange"), 0xc23e954aef3ce5a9);
}
