---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomhancocks.
--- DateTime: 24/06/2020 07:13
---

local scene = Scene.current()

print("Loading scene...")

local img = Image(Size(100, 100), Color.orange())
local entity = img:spawnEntity(Vec2(100, 100))

scene:render(function()
    print("Drawing")
    entity:draw()
end)
