on: [push]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-2019
    strategy:
      matrix:
        compiler: [clang]
        msystem: [MINGW64]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.msystem}}
        install: make cmake mingw-w64-x86_64-clang
    - run: clang --version