on: [push]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        include: [
          { installs: "MINGW32", pkg: "mcode" },
          { installs: "MINGW64", pkg: "llvm" },
        ]
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_INSTALLS: ${{ matrix.installs }}
      TARGET: ${{ matrix.pkg }}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.installs }}
          update: true
          install: base-devel git

      - name: Run build