on: [push]

jobs:
  build:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          git submodule init
          git submodule update

      - name: Run build
        uses: ./.github/actions/build_linux
