on: [push]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git cmake make mingw-w64-x86_64-toolchain mingw-w64-x86_64-clang

    - name: Install dependencies
      run: pacman -s cmake libopenal-dev libopengl-dev libglfw3-dev libglew libfreetype-dev

    - name: Run build
      run: ./.github/actions/build_msys2/entrypoint.sh
      env:
        CC: clang
        CXX: clang++