on: [push]

jobs:
  build:
    name: Build on Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest]
        msys2:
          - { msystem: MINGW64, arch: x86_64 }
        compiler:
          - { compiler: LLVM, CC: clang, CXX: clang++ }
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msys2.msystem }}
        install: |
          git
          mingw-w64-${{ matrix.msys2.arch }}-toolchain
          mingw-w64-${{ matrix.msys2.arch }}-clang
          mingw-w64-${{ matrix.msys2.arch }}-cmake
          mingw-w64-${{ matrix.msys2.arch }}-ninja

    - name: Install dependencies
      run: |
        pacman -S --noconfirm mingw-w64-x86_64-openal
        pacman -S --noconfirm mingw-w64-x86_64-mesa
        pacman -S --noconfirm mingw-w64-x86_64-glfw
        pacman -S --noconfirm mingw-w64-x86_64-glew
        pacman -S --noconfirm mingw-w64-x86_64-freetype

    - name: Run build
      env:
        CC: ${{ matrix.compiler.CC }}
        CXX: ${{ matrix.compiler.CXX }}
      run: ./.github/actions/build_msys2/entrypoint.sh