on: [push]

jobs:
  build:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"

      - uses: actions/checkout@v2

      - run: |
          git submodule init
          git submodule update

      - name: Run build
        uses: ./.github/actions/build_linux
        env:
          CC: clang
          CXX: clang++
